site_url: https://epidis.net
display_url: https://epidis.net

publish_mode: editorial_workflow
show_preview_links: true

backend:
  name: github
  repo: aroy2010/epidis-web
  branch: main
  base_url: https://epidis.net
  auth_endpoint: /api/auth

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Artículos"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}
